
package Interface;

import Controller.CheckAccount;
import javax.swing.JOptionPane;


/**
 *
 * @author brucehuynh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form PanelLogin
     */
    public Login() {
        initComponents();
        setSize(500,400);
        setLocation(400, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        usename = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        butLogin = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đăng Nhập");
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jLabel3.setText("Tài khoản ");
        jPanel1.add(jLabel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Team5", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM));

        usename.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        usename.setPreferredSize(new java.awt.Dimension(150, 30));
        usename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usenameActionPerformed(evt);
            }
        });
        usename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usenameFocusGained(evt);
            }
        });
        jPanel5.add(usename);

        jPanel1.add(jPanel5);

        jPanel4.add(jPanel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key.png"))); // NOI18N
        jLabel4.setText(" Mật khẩu ");
        jPanel2.add(jLabel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Công nghệ phần mềm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM));

        password.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        password.setPreferredSize(new java.awt.Dimension(150, 30));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel6.add(password);

        jPanel2.add(jPanel6);

        jPanel4.add(jPanel2);

        butLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/locked.png"))); // NOI18N
        butLogin.setText("Đăng Nhập");
        butLogin.setMargin(new java.awt.Insets(2, 7, 2, 14));
        butLogin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/locked.png"))); // NOI18N
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });
        jPanel7.add(butLogin);

        jPanel4.add(jPanel7);

        add(jPanel4, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    int iCount = 0;
    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        iCount ++ ;
        if(usename.equals("")){
           JOptionPane.showMessageDialog(this, "Nhập vào mã người dùng");
        }
        else {
           int t = 0 ;
           try{
               t = new Integer(usename.getText());
           }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Ma người dùng không đúng định dạng");
             return  ;
           }
           if(password.equals("")){
             JOptionPane.showMessageDialog(this,"Nhập vào mã người dùng");
           }
           else {
               if(CheckAccount.isValid(t,password.getText())){
                   new MainView().show();
                   this.setVisible(false);
                  
               }
               else  
                 JOptionPane.showMessageDialog(this, "Đăng nhập thất bại");
           }
        }
        if(iCount > 5) this.setVisible(false);
    }//GEN-LAST:event_butLoginActionPerformed

    private void usenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usenameActionPerformed
        password.requestFocus();
    }//GEN-LAST:event_usenameActionPerformed

    private void usenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usenameFocusGained
        usename.selectAll();
    }//GEN-LAST:event_usenameFocusGained

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        butLogin.doClick();
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.selectAll();
    }//GEN-LAST:event_passwordFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField usename;
    // End of variables declaration//GEN-END:variables
}
